Help with rate limiting (#9)
* new: different DOCTYPE heading

This happens if rate limited :(

* new: add selenium to base image for web automation

* new: initial attempt at working around captcha

This will work only if it is a simple 'click and hold' captcha, not an image selection captcha

* new: randomize google domain searched

* test: debug github actions

lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 1, column 2

* fix: doctype substitution and test_parser

* new: ignore 'source' tag

* test: see if the tests work better with .com only domain :/

* test: see if headers are the issue?

* test: it was the headers.. see if different domains are still okay

* test: try subset of headers?

* test: it's still a header value that's being set

* test: it has to be the 'user-agent' header

* test: debug user-agent

fix unescaping special characters

* fix: unescape needs to be done later :/

* fix: definitions can also be in spans the first time around

Since the text_ is unescaped before the regex, update the pronounciation regex

* fix: unescape calling and make sure filtered is not None

* fix: only unescape filtered if not None

* fix: add back in random headers; ignore semicolons...

* fix: it seems as if definition and example patterns have been inverted

This is because the user-agent header btw

* revert: to pre-user-agent commits

* revert: no need to track semicolons again

I hope I don't block github actions from google; the last run seemed questionable...

* fix: different countries have different spelling phonetics

* test: see if utf-8 is better decoding..

* new: try to ignore all random chars

A lot of \x blah blah and inconsistent encodings :/

* fix: str no need to decode

* fix: okay.. actually reverse

encode and then decode

* new: add override for manual completion of captcha

* fix: ignore elipsis

* fix: &#8230; is really there?

* fix: don't check for the entire entry

The encodings are super important to validate for this.. just verify that the known definitions are there

* fix: copy and paste

* fix: encodings are a pain between languages :/

* fix: use start/end of line instead of word boundaries

* fix: affair definition count

It doesn't actually matter how many there are, as long as affair and affairs have the same number

* fix: apparently this pronounciation varies greatly :s

* fix: 'google.cn' gives a weird response

don't use it